CREATE TRIGGER INSERT_AUDIT_STUDENTS AFTER INSERT ON STUDENT
FOR EACH ROW INSERT INTO 
AUDIT_STUDENT(NEW_NAME, NEW_PROGRAM, USERID, MODIFY, PROCESS, ID_STUDENT) 
VALUES (NEW.NAME, NEW.PROGRAM, CURRENT_USER(), NOW(), 'Insertar', NEW.ID);